DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserAccountStatus') THEN
    CREATE TYPE "UserAccountStatus" AS ENUM ('ACTIVE', 'LOCKED', 'SCHEDULED_DELETION', 'DEACTIVATED');
  END IF;
END $$;

ALTER TABLE IF EXISTS "account_lock_events" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "account_recovery_tokens" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "recovery_attempts" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "security_action_tokens" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "security_events" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "security_question_setup_tokens" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "security_questions" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "trusted_ips" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "user_security_questions" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "vault_activities" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "vault_credentials" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE IF EXISTS "vaults" ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "account_status" "UserAccountStatus" NOT NULL DEFAULT 'ACTIVE';
